#!/usr/bin/env bash
set -euo pipefail
trap 'error_handler $?' EXIT
ARGS="$*"

help() {
    printf "%s\n" \
        "Nix flake installer for macOS" \
        "" \
        "USAGE:" \
        "    install [OPTIONS] CONFIGURATION" \
        "" \
        "OPTIONS:" \
        "    -h, --help             Print help information" \
        "    -v, --verbose          Enable verbose logging"
}

log() {
    local clear='\033[0m'
    local level="$1"
    local color

    case "$level" in
    info) color="\033[1;32m" ;;
    verbose) color="\033[1;36m" ;;
    error) color="\033[1;31m" ;;
    *) echo "invalid log level" && exit ;;
    esac

    echo -e "$color$level:$clear ${*:2}"
}

info() { log info "$@"; }
verbose() { if $VERBOSE; then log verbose "$@"; fi; }
error() { log error "$@"; }
bail() { log error "$@" && exit; }

error_handler() {
    if [ "$1" != "0" ]; then
        error "command failed with exit status $1, aborting"
    fi
}

run() {
    if $VERBOSE; then
        "${@:1}"
    else
        "${@:1}" &>/dev/null
    fi
}

reload_shell() {
    exec bash
}

parse_args() {
    VERBOSE=false
    local positional_args=()

    while [[ $# -gt 0 ]]; do
        case $1 in
        -h | --help)
            help
            exit
            ;;
        -v | --verbose)
            VERBOSE=true
            shift
            ;;
        --* | -*)
            echo "unknown option '$1'"
            exit 1
            ;;
        *)
            positional_args+=("$1")
            shift
            ;;
        esac
    done

    CONFIG="${positional_args[0]:-}"

    if [ -z "$CONFIG" ]; then
        bail "expected configuration name as parameter"
    fi
}

install_xcode_cli_tools() {
    if xcode-select -p 1>/dev/null; then
        info "xcode cli tools already installed, skipping"
        return
    fi

    info "fetching latest xcode cli tools version"
    local xcode_version
    xcode_version="$(
        softwareupdate --list |
            grep --extended-regexp --only-matching "Command Line Tools for Xcode-\d+\.\d+" |
            head --lines 1
    )"
    info "got '$xcode_version', installing..."
    run softwareupdate --install "$xcode_version"
}

install_nix() {
    if command -v nix &>/dev/null; then
        info "nix already installed, skipping"
        return
    fi

    info "installing nix..."
    run yes | sh <(curl -L https://nixos.org/nix/install)
    reload_shell
}

install_nix_darwin() {
    if command -v darwin-rebuild &>/dev/null; then
        info "nix-darwin already installed, skipping"
        return
    fi

    info "installing nix-darwin..."
    cd "$(mktemp -d)"
    run nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz --attr installer
    run yes | ./result/bin/darwin-installer
    reload_shell
}

download_system_flake() {
    local dev_dir="$HOME/Development"
    local nix_dir="$dev_dir/nix"

    if ! [ -d "$nix_dir" ]; then
        info "downloading system flake..."
        mkdir -p "$dev_dir"
        run git clone https://github.com/opeik/nix.git "$nix_dir"
    else
        info "system flake already downloaded, skipping"
    fi
}

bootstrap_system() {
    local config="$1"
    local dev_dir="$HOME/Development"
    local nix_dir="$dev_dir/nix"

    if [ -d "/etc/profiles/per-user/$USER" ]; then
        info "system already bootstrapped, skipping"
        return
    fi

    info "building system '$config'..."
    cd "$nix_dir"
    run nix build ".#darwinConfigurations.$config.system" --extra-experimental-features "nix-command flakes"

    if ! [ -L "/etc/nix/nix.conf" ]; then
        info "moving existing nix config from \`/etc/nix/nix.conf\` to \`/etc/nix/nix.conf.old\`"
        run sudo mv -n "/etc/nix/nix.conf" "/etc/nix/nix.conf.old"
    fi

    info "bootstrapping system '$config'..."
    run ./result/sw/bin/darwin-rebuild switch --flake ".#$config"
}

switch_shell() {
    local current_shell
    local shell="/run/current-system/sw/bin/${1}"
    current_shell="$(dscl . -read ~/ UserShell | sed 's/UserShell: //')"

    if [ "$current_shell" = "$shell" ]; then
        info "shell already set, skipping"
        return
    fi

    info "setting shell to '$1'..."
    run sudo chsh -s "$shell" "$USER"
}

main() {
    parse_args "$ARGS"
    install_xcode_cli_tools
    install_nix
    install_nix_darwin
    download_system_flake
    bootstrap_system "$CONFIG"
    switch_shell fish
    info "done!"
}

main
