#!/usr/bin/env bash

set -euo pipefail

help() {
    printf "%s\n" \
        "Nix flake installer for macOS" \
        "" \
        "USAGE:" \
        "    install [OPTIONS] [HOST]" \
        "" \
        "OPTIONS:" \
        "    -h, --help             Print help information" \
        "    -v, --verbose          Enable command output"
}

info() {
    local green='\033[1;32m'
    local clear='\033[0m'
    echo -e "${green}info:${clear} ${1}"
}

verbose() {
    local blue='\033[1;36m'
    local clear='\033[0m'
    if $VERBOSE; then
        echo -e "${blue}verbose:${clear} ${1}"
    fi
}

run() {
    if $VERBOSE; then
        "${@:1}"
    else
        "${@:1}" &>/dev/null
    fi
}

reload_shell() {
    exec bash
}

install_xcode_cli_tools() {
    if xcode-select -p 1>/dev/null; then
        info "xcode cli tools already installed, skipping"
        return
    fi

    info "fetching latest xcode cli tools version"
    local xcode_version
    xcode_version="$(
        softwareupdate --list |
            grep --extended-regexp --only-matching "Command Line Tools for Xcode-\d+\.\d+" |
            head --lines 1
    )"
    info "got '$xcode_version', installing..."
    run softwareupdate --install "$xcode_version"
}

install_nix() {
    if command -v nix &>/dev/null; then
        info "nix already installed, skipping"
        return
    fi

    info "installing nix..."
    run yes | sh <(curl -L https://nixos.org/nix/install)
    reload_shell
}

install_nix_darwin() {
    if command -v darwin-rebuild &>/dev/null; then
        info "nix-darwin already installed, skipping"
        return
    fi

    info "installing nix-darwin..."
    cd "$(mktemp -d)"
    run nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz --attr installer
    run yes | ./result/bin/darwin-installer
    reload_shell
}

install_system_flake() {
    local host="$1"
    local nix_dir="$HOME/Development/nix"

    mkdir -p "$nix_dir"

    if ! [ -d "$nix_dir" ]; then
        info "fetching system flake repo..."
        git clone --quiet https://github.com/opeik/nix.git "$nix_dir"
    else
        info "updating system flake repo..."
        git -C "$nix_dir" pull --quiet
    fi

    info "building system configuration '$host'..."
    cd "$nix_dir"
    nix build ".#darwinConfigurations.$host.system" --extra-experimental-features "nix-command flakes"

    local files=(/etc/shells /etc/nix/nix.conf)
    for file in "${files[@]}"; do
        if ! [ -L "$file" ]; then
            info "deleting non-symlinked system file '$file'"
            sudo rm "$file"
        fi
    done

    info "switching to system configuration '$host'..."
    run ./result/sw/bin/darwin-rebuild switch --flake ".#$host"
}

switch_shell() {
    local current_shell
    local shell="/run/current-system/sw/bin/${1}"
    current_shell="$(dscl . -read ~/ UserShell | sed 's/UserShell: //')"

    if [ "$current_shell" = "$shell" ]; then
        info "shell already set to '$1', skipping"
        return
    fi

    info "setting shell to '$1'..."
    sudo chsh -s "$shell" "$USER"
}

# Parse command line arguments.
POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
    case $1 in
    -h | --help)
        help
        exit
        ;;
    -v | --verbose)
        VERBOSE=true
        shift
        ;;
    -* | --*)
        echo "unknown option '$1'"
        exit 1
        ;;
    *)
        POSITIONAL_ARGS+=("$1")
        shift
        ;;
    esac
done

VERBOSE=false
HOST="${POSITIONAL_ARGS[0]:-reimu}"

main() {
    install_xcode_cli_tools
    install_nix
    install_nix_darwin
    install_system_flake "$HOST"
    switch_shell fish
}

main
