name: ci

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

permissions:
  contents: read

jobs:
  eval:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        system: [reimu, marisa, work]
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: samueldr/lix-gha-installer-action@latest

      - name: Evaluate system `${{ matrix.system }}`
        run: nix eval --show-trace .#darwinConfigurations.${{ matrix.system }}.config.system.build.toplevel.drvPath
